apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod 
spec:
  volumes:
  - name: multicontainer-log
    emptyDir: {}
  containers:
  - name: app-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"]
    volumeMounts:
    - name: multicontainer-log
      mountPath: /var/log
